--<ScriptOptions statementTerminator=";"/>

CREATE TABLE tepTin (
	idFile VARCHAR(35) NOT NULL,
	data MEDIUMBLOB NOT NULL,
	ngayGui DATE,
	tenFile VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE banBe (
	id1 VARCHAR(35) NOT NULL,
	id2 VARCHAR(35) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE tinNhan (
	idNhan VARCHAR(35) NOT NULL,
	idGui VARCHAR(35) NOT NULL,
	noiDung VARCHAR(500) NOT NULL,
	idFile VARCHAR(300),
	ngayGui DATE NOT NULL
) ENGINE=InnoDB;

CREATE TABLE nhom (
	idNhom VARCHAR(35) NOT NULL,
	nguoiTao VARCHAR(70) NOT NULL,
	hinhAnh VARCHAR(70) NOT NULL,
	note VARCHAR(500),
	PRIMARY KEY (idNhom)
) ENGINE=InnoDB;

CREATE TABLE thongtin (
	id VARCHAR(35) NOT NULL,
	nguoiDung VARCHAR(70) NOT NULL,
	email VARCHAR(50) NOT NULL,
	ten VARCHAR(70) NOT NULL,
	matKhau VARCHAR(500) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB;

