--<ScriptOptions statementTerminator=";"/>

CREATE TABLE thongtin (
	nguoiDung VARCHAR(70) NOT NULL,
	email VARCHAR(50) NOT NULL,
	ten VARCHAR(35) NOT NULL,
	matKhau VARCHAR(500) NOT NULL,
	PRIMARY KEY (ten)
) ENGINE=InnoDB;

CREATE TABLE banBe (
	id1 VARCHAR(35) NOT NULL,
	id2 VARCHAR(35) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE tinNhan (
	idNhan VARCHAR(35) NOT NULL,
	idGui VARCHAR(35) NOT NULL,
	noiDung VARCHAR(500) NOT NULL,
	idFile VARCHAR(300),
	ngayGui TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL
) ENGINE=InnoDB;

CREATE TABLE tepTin (
	idFile VARCHAR(35) NOT NULL,
	data MEDIUMBLOB NOT NULL,
	ngayGui DATE,
	tenFile VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE tvNhom (
	idNhom VARCHAR(35) NOT NULL,
	idTV VARCHAR(35) NOT NULL,
	quyen VARCHAR(10)
) ENGINE=InnoDB;

CREATE TABLE nhom (
	idNhom VARCHAR(35) NOT NULL,
	nguoiTao VARCHAR(70) NOT NULL,
	hinhAnh VARCHAR(70),
	note VARCHAR(500),
	tenNhom VARCHAR(70) NOT NULL,
	PRIMARY KEY (idNhom)
) ENGINE=InnoDB;

CREATE INDEX idGui ON tinNhan (idGui ASC);

CREATE INDEX id1 ON banBe (id1 ASC);

CREATE INDEX idTV ON tvNhom (idTV ASC);

CREATE INDEX idNhom ON tvNhom (idNhom ASC);

CREATE INDEX id2 ON banBe (id2 ASC);

